name: Check, build and release

on:
  pull_request:
    branches:
    - develop
    - master
  push:
    branches:
    - develop
    - master
    tags:
    - "v*.*.*"


jobs:
  build_and_release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.9'

      - name: Install build tools
        run: pip install build twine

      - name: Build wheel
        run: python -m build

      - name: Check build
        run: twine check dist/*

      - name: Publish build to pypi
        run: twine upload dist/*

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: dist/*
